name: flutter_app_test
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  english_words: ^3.1.5
  flutter:
    sdk: flutter
cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
